CREATE TABLE `userSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`bio` text,
	`avatarUrl` varchar(500),
	`linkedinConnected` int DEFAULT 0,
	`xConnected` int DEFAULT 0,
	`instagramConnected` int DEFAULT 0,
	`linkedinApiKey` text,
	`xApiKey` text,
	`instagramApiKey` text,
	`defaultVisibility` varchar(20) DEFAULT 'public',
	`autoSaveFrequency` int DEFAULT 30,
	`defaultPlatformId` int,
	`timezone` varchar(50) DEFAULT 'America/Chicago',
	`emailNotifications` int DEFAULT 1,
	`calendarReminders` int DEFAULT 1,
	`weeklyReports` int DEFAULT 1,
	`companyLogoUrl` varchar(500),
	`brandColorPrimary` varchar(20) DEFAULT '#3B82F6',
	`brandColorSecondary` varchar(20) DEFAULT '#EAB308',
	`defaultHashtags` text,
	`signatureText` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `userSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `userSettings_userId_unique` UNIQUE(`userId`)
);
